### PR TITLE
Add a pretty snap store button.

### PR DESCRIPTION
**Pull request by popey**
A white alternative button is also available. https://snapcraft.io/static/images/badges/en/snap-store-white.svg
No problem if you'd rather keep it text only :) 
Thanks for making such a fun game :)

### CODE REVIEW

**Comment by msokalski** [comment]
I've chosen white version. Thank you
Btw,do you know if there is any chance for me to see install stats from your snap? 
... or I'm limited only to that silly world map?

**Comment by popey** [comment]
There's a few options here. 
1) I get the stats and send them to you
2) I add you as a "collaborator" on the snap, then you can login and see them yourself (and are able to fully manage the snap too)
3) I transfer the snap to you (which is effectively the same as 2) but the ownership [and responsibility for updates] is switched to you).

3 would be great, I can provide the `snapcraft.yaml` and build instructions. 
2 is fine if you don't have time or inclination
1 is fine, but least-preferred option. 

Up to you. I don't mind.

Here's what it looks like with near-zero promotion.

image

**Comment by msokalski** [comment]
Oh! Thank you, thank you!
I think I can try to be maintainer of it. I'd be very grateful for build instructions. My account on ubuntu1 is same as here: msokalski

**Comment by popey** [comment]
Awesome, super news.

Ok, I will send an invite to make you a collaborator from the store. 
This repo contains the yaml and other bits needed to make the snap https://github.com/popey/ascii-patrol-snap . essentially just merge the contents of that into your tree. (feel free to replace the awful icon I made). Once that's in your master branch, visit build.snapcraft.io and click the green button to enable automatic builds directly from master to the edge channel in the store. (that will only work once the yaml is in master and you accept the offer to collaborate on the snap which you will get via email).

Once you're happy I can ask the store team to swap ownership of the snap from me to you. Then we're done :) 

(I'm happy to help if you get any issues with building the snap, but we also have a [forum](https://forum.snapcraft.io/) where a community of friendly people can help too)

**Comment by msokalski** [comment]
Excellent,
I'm almost done but, build.snapcraft.io doesn't let me re-use 'ascii-patrol' registered name. This is probably because what I'm actually doing is creating a new snap based on my github's repo. Any hint how should I do it without creating a new registered name for it?
Many many thanks popey!

**Comment by popey** [comment]
I had it setup under my account, but that shouldn't prevent you from doing so too. However, I have deleted it from my account on build.snapcraft.io. What happens if you try to add it again? It may be a bug, and we can get the web team to look at it. We don't want to change the name, I think.

**Comment by msokalski** [comment]
Here I am, same thing happens. I feel a bit confused as I'm not modifying anything in the old snap, rather trying to register new one. I've looked into your snap settings but I couldn't find anything like change source repo :(. Or, should I click that 'file a claim' link?
untitled-1

**Comment by popey** [comment]
As a collaborator it *should* let you upload. I don't understand why it isn't. The easiest fix is for me to put in a request to the store team to get the snap transferred to you. I've done that [here](https://forum.snapcraft.io/t/please-transfer-ascii-patrol/9844).

**Comment by msokalski** [comment]
It worked! Thank you for your assistance.

**Comment by popey** [comment]
You now own the snap. Thanks for taking it on. Feel free to ping me or the forum if you get any more questions :)

**Comment by msokalski** [comment]
Hey, thanks for letting me know about launcher +x issue, I hope it is fixed now. Btw, how did you send me such 'github notification' ?

**Comment by popey** [comment]
No problem. I just created a new issue #9 which I guess sent you a mail / notification :)

**Pull request merged**
