### PR TITLE
xm player: add slides, vibrato

### PR DESCRIPTION
**Pull request by hexwab**
I admit to being curious as to the origin of this player :)

### CODE REVIEW

**Comment by msokalski** [comment]
I've written it specifically for ascii patrol, based on some annoying and leaky specs. 
I'll try your patch tomorrow. Does it sound closer to the original: https://indiegamemusic.com/viewtrack.php?id=32

Thanks!

**Comment by hexwab** [comment]
Ha, I suspected as much! (What other reason could there be for having a case handling downwards slides but not upwards ones, other than that the specific tune you wrote it for contains examples of the former but not the latter? To say nothing of the hardcoded loop points...)

I am aware how desperately incomplete the specs are.[1] Happily this is not my first XM player.
I have only tested my changes with this particular tune and have not tried my usual bunch of test tunes. But I like the idea of keeping it minimalist and not implementing unneeded corner cases.

I already managed to extract the mo3 file and load it up in OpenMPT[2] (hence I noticed differences that ultimately resulted in the above patch). But having the lossless source is always good. I had to change the looping because after the addition of the slides at position 20 the loop back to the beginning sounded terrible: having the source would make changing the tune itself to be more amenable to looping there easier.

Speaking of which, I'm not sure what the best plan wrt looping is. Even with the game over portion of the tune included in the main game loop it's almost impossible to play long enough to get that far (at least for me), which is good. But it's perfectly possible to stay too long on the (delightfully OTT) title screen until the main game portion of the tune arrives, at which point when you start the game the music fades out and exactly the same music you were just listening to starts again.

[1] So much so it's almost comical. "This should be just about everything (I hope?)." <-- ORLY?

[2] https://sphere.chronosempire.org.uk/~HEx/mpjs/#mods/asciipatrol.xm;loop is the result converted back to xm by OpenMPT and rendered in-browser for your convenience.  For comparison here's the source xm you linked: https://sphere.chronosempire.org.uk/~HEx/mpjs/#mods/I%20am%20your%20product.xm
On cursory listening the only difference I note is the silence in the final pattern, which I'm guessing you changed for the between-level cutscenes.

**Comment by msokalski** [comment]
Wow, pitch slides work too :)
Thank you @hexwab for such great contribution!

**Comment by msokalski** [comment]
Released 1.6

**Pull request merged**
